name: docker-ci

on:
  push:
    branches:
    - "main"
  pull_request:
    branches: 
    - "main"
    - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Artifact Registry/GCR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - uses: actions/checkout@v2
      - name: Build & Publish the Docker image
        run: |
          docker buildx create --name builder --use --platform=linux/amd64,linux/arm64  && docker buildx build --platform=linux/amd64,linux/arm64 . -t  us-docker.pkg.dev/covalent-project/network/ipfs-pinner:latest --push
